version: '3.6'
services: 
    node:
        build: docker/node
        restart: unless-stopped
        ports: 
            - "80:3000"
        volumes: 
            - "./client:/www"


            
# services -    контейнеры (в данном случае только один - node)
#               их можно содавать любое количество и каждый будет создан (build: docker/node)
#               на основании своего Dockerfile (например можно для каждого контейнера установить свою версию ноды)


